# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["Webwedd.csproj", "./"]

RUN dotnet restore "Webwedd.csproj"

COPY . .

RUN dotnet publish "Webwedd.csproj" \
    -c Release \
    -o /app/publish \
    /p:UseAppHost=false


# Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_HTTP_PORTS=10000

EXPOSE 10000

ENTRYPOINT ["dotnet", "Webwedd.dll"]